---

name: unit-tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: unit-tests

    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          always-auth: false
          node-version: ${{ matrix.node-version }}

      - name: Run npm install
        run: npm install

      - name: Run Tests
        run: npm run test

  automerge:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
